#!/usr/bin/env python

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

from itertools import takewhile

def euler_2():
    g = fib_gen(1, 2)

    vals = (x for x in takewhile(lambda x: x < 4000000, g) if x % 2 == 0)
    return sum(vals)

def fib_gen(a, b):
    while True:
        yield a
        a, b = b, a + b

if __name__ == "__main__":
    print(euler_2())
